language: csharp
dotnet: 2.0.0
dist: trusty
solution: ./src/Moq.EntityFrameworkCore.sln
script:
  - cd src
  - dotnet restore
  - dotnet build --configuration=Release
  - dotnet test ./Moq.EntityFrameworkCore.Tests/Moq.EntityFrameworkCore.Tests.csproj
  - dotnet test ./Moq.EntityFrameworkCore.Examples/Moq.EntityFrameworkCore.Examples.csproj
  